Veil/Veil/Controllers/GamesController.cs
/* GamesController.cs
 * Purpose: Controller for the Games model
 * 
 * Revision History:
 *      Isaac West, 2015.10.13: Created
 */ 

using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Veil.DataAccess.Interfaces;
using Veil.DataModels.Models;
using Veil.Helpers;
using Veil.Models;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Transactions;
using System.Web;
using System.Web.Routing;
using LinqKit;
using Veil.Extensions;
using Veil.DataModels;

namespace Veil.Controllers
{
    /// <summary>
    ///     Controller for actions related to <see cref="Game"/>
    /// </summary>
    public class GamesController : BaseController
    {
        private const int GAMES_PER_PAGE = 10;

        private readonly IVeilDataAccess db;
        private readonly IGuidUserIdGetter idGetter;

        /// <summary>
        ///     Instantiates a new instance of GamesController with the provided argument
        /// </summary>
        /// <param name="veilDataAccess">
        ///     The <see cref="IVeilDataAccess"/> to use for database access
        /// </param>
        /// <param name="idGetter">
        ///     The <see cref="IGuidUserIdGetter"/> to use for getting the current user's Id
        /// </param>
        public GamesController(IVeilDataAccess veilDataAccess, IGuidUserIdGetter idGetter)
        {
            db = veilDataAccess;
            this.idGetter = idGetter;
        }

        public int GamesPerPage { get; set; } = GAMES_PER_PAGE;

        /// <summary>
        ///     Displays a paginated list of games
        /// </summary>
        /// <param name="page">
        ///     The page number being requested
        /// </param>
        /// <returns>
        ///     A paginated list of games
        /// </returns>
        public async Task<ActionResult> Index(int page = 1)
        {
            var viewModel = new GameListViewModel
            {
                CurrentPage = page
            };

            IQueryable<Game> games = db.Games;

            games = FilterOutInternalOnly(games).OrderBy(g => g.Name);

            viewModel.Games = await games.
                Skip((viewModel.CurrentPage - 1) * GamesPerPage).
                Take(GamesPerPage).
                ToListAsync();

            viewModel.TotalPages = 
                (int) Math.Ceiling(await games.CountAsync() / (float) GamesPerPage);

            return View(viewModel);
        }

        /// <summary>
        ///     Processes simple search game search. This is used by the nav-bar search
        /// </summary>
        /// <param name="keyword">
        ///     Fragment of a game title to filter by
        /// </param>
        /// <param name="page">
        ///     The page number being requested
        /// </param>
        /// <returns>
        ///     IQueryable of type 'Game' to Index view of Games controller.
        /// </returns>
        public async Task<ActionResult> Search(string keyword = "", int page = 1)
        {
            var viewModel = new GameListViewModel
            {
                CurrentPage = page
            };

            keyword = keyword.Trim();

            IQueryable<Game> gamesFiltered;

            if (!string.IsNullOrWhiteSpace(keyword))
            {
                gamesFiltered = db.Games
                    .Where(g => g.Name.Contains(keyword));
            }
            else
            {
                gamesFiltered = db.Games;
            }

            gamesFiltered = FilterOutInternalOnly(gamesFiltered).OrderBy(g => g.Name);

            ViewBag.SearchTerm = keyword;

            viewModel.Games = await gamesFiltered.
                Skip((viewModel.CurrentPage - 1) * GamesPerPage).
                Take(GamesPerPage).
                ToListAsync();

            viewModel.TotalPages = 
                (int) Math.Ceiling(await gamesFiltered.CountAsync() / (float) GamesPerPage);

            return View("Index", viewModel);
        }

        /// <summary>
        ///     Processes advanced game searches and displays the results
        /// </summary>
        /// <param name="tags">
        ///     List of tag names to filter by
        /// </param>
        /// <param name="title">
        ///     Title search string to filter by
        /// </param>
        /// <param name="platform">
        ///     Platform Code for the platform to filter by
        /// </param>
        /// <param name="page">
        ///     The page number being requested
        /// </param>
        /// <returns>
        ///     Index view with the filtered results
        /// </returns>
        public async Task<ActionResult> AdvancedSearch(
            List<string> tags, string title = "", string platform = "", int page = 1)
        {
            page = page < 1 ? 1 : page;

            title = title.Trim();
            platform = platform.Trim();
            tags = tags ?? new List<string>();

            if (tags.Count == 0 && title == "" && platform == "")
            {
                AdvancedGameSearchViewModel advancedGameAdvancedGameSearchViewModel = new AdvancedGameSearchViewModel
                {
                    Platforms = await db.Platforms.ToListAsync()
                };

                return View(advancedGameAdvancedGameSearchViewModel);
            }

            for (int i = 0; i < tags.Count; i++)
            {
                string t = tags[i];
                t = t.Trim();
                tags[i] = t;
            }

            // We are doing Or, so we need the first to be false
            var searchPredicate = PredicateBuilder.False<Game>();

            if (!string.IsNullOrWhiteSpace(title))
            {
                // Filter by title
                searchPredicate = searchPredicate.Or(g => g.Name.Contains(title));
            }
                
            if (tags.Count > 0)
            {
                // Filter by tags
                searchPredicate = searchPredicate.Or(g => g.Tags.Any(t => tags.Contains(t.Name)));
            }

            if (!string.IsNullOrWhiteSpace(platform))
            {
                // Filter by platform
                searchPredicate = searchPredicate.Or(
                    g => g.GameSKUs.Any(gs => gs.PlatformCode == platform));
            }

            if (!User.IsEmployeeOrAdmin())
            {
                // Filter out any not for sale games
                // We are doing And, so we need the first to be true
                var roleFilterPredicate = PredicateBuilder.True<Game>().
                    And(g => g.GameAvailabilityStatus != AvailabilityStatus.NotForSale);

                // Equivalent to (conditionAbove && (searchPredicateConditions))
                searchPredicate = roleFilterPredicate.And(searchPredicate);
            }

            IQueryable<Game> gamesFiltered = db.Games.AsExpandable().
                Where(searchPredicate).
                OrderBy(g => g.Name);

            string platformName =
                await db.Platforms.
                    Where(p => p.PlatformCode == platform).
                    Select(p => p.PlatformName).
                    FirstOrDefaultAsync();

            string searchQuery = $"{title}, ";

            if (platformName != null)
            {
                searchQuery += $"{platformName}, ";
            }

            searchQuery += string.Join(", ", tags);
                
            ViewBag.SearchTerm = searchQuery.Trim(',', ' ');

            var gamesListViewModel = new GameListViewModel()
            {
                CurrentPage = page
            };

            gamesListViewModel.Games = await gamesFiltered.
                Skip((gamesListViewModel.CurrentPage - 1) * GamesPerPage).
                Take(GamesPerPage).
                ToListAsync();

            gamesListViewModel.TotalPages = 
                (int) Math.Ceiling(await gamesFiltered.CountAsync() / (float) GamesPerPage);

            return View("Index", gamesListViewModel);
        }

        /// <summary>
        ///     Gets the 10 best matches to the current member's favorite platforms and tags.
        ///     Current recommendation is sorted as follows:
        ///         Games with at least one GameSku matching any of the member's favorite platforms
        ///             AND at least one tag matching the member's favorite tags.
        ///         Games with at least one tag matching, but no platforms.
        ///         These first two categories are sorted by the number of tags that match the member's favorites.
        ///         Games with at least platform matching, but no tags.
        ///         Each of these three sections are last sorted by release date with newest games first.
        ///     A game that a member has already purchased (regardless of format) will never be recommended.
        /// </summary>
        /// <returns>
        ///     A view with the filtered list of games
        /// </returns>
        [Authorize(Roles = VeilRoles.MEMBER_ROLE)]
        public async Task<ActionResult> Recommended()
        {
            Member currentMember = await db.Members.FindAsync(idGetter.GetUserId(User.Identity));

            if (currentMember.FavoritePlatforms.Count + currentMember.FavoriteTags.Count == 0)
            {
                this.AddAlert(AlertType.Info, "You do not have any favorite platforms or tags yet.");
                return RedirectToAction("Index", "Manage");
            }
            
            var tagGames = currentMember.FavoriteTags
                .SelectMany(t => t.TaggedGames)
                .Where(g => g.GameAvailabilityStatus != AvailabilityStatus.NotForSale)
                .ToList();

            var platformGames = currentMember.FavoritePlatforms
                .SelectMany(p => p.GameProducts)
                .Select(gp => gp.Game)

Veil/Veil/Controllers/TagsController.cs
/* TagsController.cs
 * Purpose: Controller for displaying checkboxes for all Tags
 * 
 * Revision History:
 *      Kyle Zimmerman, 2015.11.03: Created
 */

using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Veil.DataAccess.Interfaces;
using Veil.DataModels.Models;
using Veil.Models;

namespace Veil.Controllers
{
    /// <summary>
    ///     Controller for displaying checkboxes for all Tags
    /// </summary>
    public class TagsController : BaseController
    {
        private readonly IVeilDataAccess db;

        /// <summary>
        ///     Instantiates a new instance of TagsController with the provided arguments
        /// </summary>
        /// <param name="veilDataAccess">
        ///     The <see cref="IVeilDataAccess"/> to use for database access
        /// </param>
        public TagsController(IVeilDataAccess veilDataAccess)
        {
            db = veilDataAccess;
        }

        /// <summary>
        ///     Produces a partial view containing a checkbox for each Tag.
        /// </summary>
        /// <param name="selected">
        ///     The list of tags to set as selected
        /// </param>
        /// <returns>
        ///     The partial view to be rendered
        /// </returns>
        [ChildActionOnly]
        public PartialViewResult Index(List<Tag> selected)
        {
            var tagsViewModel = new TagViewModel()
            {
                AllTags = db.Tags.ToList(),
                Selected = selected
            };

            return PartialView(tagsViewModel);
        }
    }
}

Veil/Veil/Views/Games/AdvancedSearch.cshtml
@using Veil.DataModels.Models
@model Veil.Models.AdvancedGameSearchViewModel

@{
    ViewBag.Title = "Advanced Search";
}

<div class="row">
    <div class="column">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

@using (Html.BeginForm("AdvancedSearch", "Games", FormMethod.Get))
{
    <div class="row">
        <div class="medium-2 columns">
            <label for="game-name">Name:</label>
        </div>
        <div class="medium-4 columns">
            <input type="text" id="game-name" name="title" />
        </div>
        <div class="medium-2 columns">
            <label for="game-name">Platform:</label>
        </div>
        <div class="medium-4 columns">
            <select id="game-platform" name="platform">
                <option value="">-- Any Platform --</option>
                @foreach (var platform in Model.Platforms)
                {
                    <option value="@platform.PlatformCode">@platform.PlatformName</option>
                }
            </select>
        </div>
    </div>
    <div class="row collapse">
        <div class="medium-4 large-2 columns">
            @Html.Label($"{nameof(Tag)}s", new {@class = "prefix"})
        </div>
        <div class="medium-8 large-10 columns panel">
            @{ Html.RenderAction("Index", "Tags"); }
        </div>
    </div>

    <div class="row">
        <div class="medium-push-9 medium-3 columns">
            <button class="expand">Search</button>
        </div>
    </div>
}

Veil/Veil/Views/Games/Create.cshtml
@model Veil.DataModels.Models.Game

@{
    ViewBag.Title = "Create Game";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="medium-10 medium-centered  column">
            <h2>@ViewBag.Title</h2>
            @Html.ValidationSummary(true, "", new {@class = "text-danger"})


            <div class="row collapse">
                <div class="small-12 medium-4 large-2 columns">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "prefix"})
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "expand"}})
                    @Html.ValidationMessageFor(model => model.Name, "", new {@class = ""})
                </div>
            </div>

            <div class="row">
                <div class="large-6 columns">
                    <div class="row collapse">
                        <div class="medium-4 columns">
                            @Html.LabelFor(model => model.MinimumPlayerCount, htmlAttributes: new { @class = "prefix" })
                        </div>
                        <div class="medium-8 columns">
                            @Html.EditorFor(model => model.MinimumPlayerCount, new { htmlAttributes = new { @class = "expand" } })
                            @Html.ValidationMessageFor(model => model.MinimumPlayerCount, "", new { @class = "" })
                        </div>
                    </div>
                </div>
                <div class="large-6 columns">
                    <div class="row collapse">
                        <div class="medium-4 columns">
                            @Html.LabelFor(model => model.MaximumPlayerCount, htmlAttributes: new { @class = "prefix" })
                        </div>
                        <div class="medium-8 columns">
                            @Html.EditorFor(model => model.MaximumPlayerCount, new { htmlAttributes = new { @class = "expand" } })
                            @Html.ValidationMessageFor(model => model.MaximumPlayerCount, "", new { @class = "" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.PrimaryImageURL, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.PrimaryImageURL, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.PrimaryImageURL, "", new { @class = "" })
                </div>
            </div>
            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.TrailerURL, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.TrailerURL, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.TrailerURL, "", new { @class = "" })
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "" })
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.LongDescription, htmlAttributes: new {@class = "prefix"})
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.LongDescription, new {htmlAttributes = new {@class = ""}})
                    @Html.ValidationMessageFor(model => model.LongDescription, "", new {@class = ""})
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.ESRBRatingId, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.DropDownListFor(model => model.ESRBRatingId, null, htmlAttributes: new { @class = "" })
                    @Html.ValidationMessageFor(model => model.ESRBRatingId, "", new { @class = "" })
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.ContentDescriptors, new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns panel">
                    @{ Html.RenderAction("Index", "ESRBDescription", new { selected = Model?.ContentDescriptors?.ToList() }); }
                    @Html.ValidationMessageFor(model => model.ContentDescriptors, "", new { @class = "" })
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.Tags, new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns panel">
                    @{ Html.RenderAction("Index", "Tags", new { selected = Model?.Tags?.ToList() }); }
                    @Html.ValidationMessageFor(model => model.Tags, "", new { @class = "" })
                </div>
            </div>

            <button type="submit" class="right expand">Create Game</button>
        </div>
</div>
}

Veil/Veil/Views/Games/Delete.cshtml
@model Veil.DataModels.Models.Game

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="columns">
        <h2>Delete @Model.Name</h2>

        <div>
            <h3>Are you sure you want to continue?</h3>
            <hr />

            <p>
                <strong>@Html.DisplayNameFor(model => model.Name): </strong>
                @Html.DisplayFor(model => model.Name)
            </p>

            <p>
                <strong>@Html.DisplayNameFor(model => model.ESRBRatingId): </strong>
                @Html.DisplayFor(model => model.ESRBRatingId)
            </p>

            <p>
                <strong>@Html.DisplayNameFor(model => model.ShortDescription): </strong>
                @Html.DisplayFor(model => model.ShortDescription)
            </p>

            @if (Model.GameSKUs != null && Model.GameSKUs.Any())
            {
                <div class="panel">
                    <h4>By deleting this game you will also be deleting the following SKUs:</h4>

                    @foreach (var game in Model.GameSKUs)
                    {
                        <p>
                            <strong>@Html.DisplayNameFor(m => game.Platform.PlatformName): </strong>@game.Platform.PlatformName
                            <br />
                            <strong>SKU Name: </strong>@game.Name
                        </p>
                    }
                </div>

            }

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.ActionLink("Cancel", "Details", new { Id = Model.Id }, new { @class = "button" })
                <input type="submit" value="Delete" class="button alert right" />
            }
        </div>
    </div>
</div>

Veil/Veil/Views/Games/DeleteGameProduct.cshtml
@model Veil.DataModels.Models.GameProduct

@{
    ViewBag.Title = "DeleteGameProduct";
}

<div class="row">
    <div class="columns">
        <h2>Delete @Model.Platform.PlatformName @Model.Name</h2>
        <h3>Are you sure you want to delete this?</h3>
            <hr />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <ul class="button-group">
                    <li><input type="submit" value="Delete" class="button alert" /></li>
                    <li>@Html.ActionLink("Cancel", "Index", null, new { @class = "button" })</li>
                </ul>
            }
    </div>
</div>

Veil/Veil/Views/Games/Edit.cshtml
@using Veil.DataModels.Models
@model Game

@{
    ViewBag.Title = $"Edit '{Model.Name}'";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="medium-10 medium-centered  column">
            <h2>@ViewBag.Title</h2>
            @Html.ValidationSummary(false)

            <div class="row collapse">
                <div class="small-12 medium-4 large-2 columns">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "" })
                </div>
            </div>

            <div class="row">
                <div class="large-6 columns">
                    <div class="row collapse">
                        <div class="medium-4 columns">
                            @Html.LabelFor(model => model.MinimumPlayerCount, htmlAttributes: new { @class = "prefix" })
                        </div>
                        <div class="medium-8 columns">
                            @Html.EditorFor(model => model.MinimumPlayerCount, new { htmlAttributes = new { @class = "expand" } })
                            @Html.ValidationMessageFor(model => model.MinimumPlayerCount, "", new { @class = "" })
                        </div>
                    </div>
                </div>
                <div class="large-6 columns">
                    <div class="row collapse">
                        <div class="medium-4 columns">
                            @Html.LabelFor(model => model.MaximumPlayerCount, htmlAttributes: new { @class = "prefix" })
                        </div>
                        <div class="medium-8 columns">
                            @Html.EditorFor(model => model.MaximumPlayerCount, new { htmlAttributes = new { @class = "expand" } })
                            @Html.ValidationMessageFor(model => model.MaximumPlayerCount, "", new { @class = "" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.PrimaryImageURL, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.PrimaryImageURL, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.PrimaryImageURL, "", new { @class = "" })
                </div>
            </div>
            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.TrailerURL, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.TrailerURL, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.TrailerURL, "", new { @class = "" })
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "expand" } })
                    @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "" })
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.LongDescription, htmlAttributes: new {@class = "prefix"})
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.EditorFor(model => model.LongDescription, new {htmlAttributes = new {@class = ""}})
                    @Html.ValidationMessageFor(model => model.LongDescription, "", new {@class = ""})
                </div>
            </div>


            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.ESRBRatingId, htmlAttributes: new {@class = "prefix"})
                </div>
                <div class="medium-8 large-10 columns">
                    @Html.DropDownListFor(model => model.ESRBRatingId, null)
                    @Html.ValidationMessageFor(model => model.ESRBRatingId, "")
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.ContentDescriptors, new { @class = "prefix" })
                </div>
                <div class="medium-8 large-10 columns panel">
                    @{ Html.RenderAction("Index", "ESRBDescription", new { selected = Model.ContentDescriptors.ToList() }); }
                    @Html.ValidationMessageFor(model => model.ContentDescriptors, "")
                </div>
            </div>

            <div class="row collapse">
                <div class="medium-4 large-2 columns">
                    @Html.LabelFor(model => model.Tags, new {@class = "prefix"})
                </div>
                <div class="medium-8 large-10 columns panel">
                    @{ Html.RenderAction("Index", "Tags", new {selected = Model.Tags.ToList()}); }
                    @Html.ValidationMessageFor(model => model.Tags, "", new {@class = ""})
                </div>
            </div>

            <div class="row">
                <div class="medium-10 column">
                    <button type="submit" class="expand">Save Changes</button>
                </div>
                <div class="medium-2 column">
                    @Html.ActionLink("Cancel", "Details", new { id = Model.Id }, new { @class = "button alert expand" })
                </div>
            </div>
        </div>
    </div>
}

Veil/Veil/Views/Games/Search.cshtml
@model Veil.Models.SearchViewModel

@{
    ViewBag.Title = "Advanced Search";
}

<div class="row">
    <div class="column">
        <h2>@ViewBag.Title</h2>
    </div>
</div>

@using (Html.BeginForm("Search", "Games", FormMethod.Post))
{
    <div class="row">
        <div class="medium-2 columns">
            <label for="game-name">Name:</label>
        </div>
        <div class="medium-4 columns">
            <input type="text" id="game-name" name="title" />
        </div>
        <div class="medium-2 columns">
            <label for="game-name">Platform:</label>
        </div>
        <div class="medium-4 columns">
            <select id="game-platform" name="platform">
                @foreach (var platform in Model.Platforms)
                {
                    <option value="@platform.PlatformCode">@platform.PlatformName</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="medium-2 columns">
            <label for="game-name">Tags:</label>
        </div>
        <div class="medium-10 columns">
            @foreach (var tag in Model.Tags)
            {
                <div style="display: inline-block">
                    <input type="checkbox" id="tag-@tag.Name" name="tags" value="@tag.Name" /><label for="tag-@tag.Name">@tag.Name</label>
                </div>
            }
        </div>
    </div>

    <div class="row">
        <div class="medium-push-9 medium-3 columns">
            <button class="expand">Search</button>
        </div>
    </div>
}

Veil/Veil/Views/Games/_DownloadGameProduct.cshtml
@using Veil.DataModels.Models
@using Veil.Extensions
@model DownloadGameProduct

<div class="small-3 columns" data-equalizer-watch>
    @{ var rating = Model.AverageRating; }
    @if (rating.HasValue)
    {
        <div class="row">
            <strong class="label info column bordered">Average Rating</strong>
        </div>

        <div class="row">
            <div class="column text-center margin-bottom-1 bordered rating">
                @Html.Partial("_RatingStarsPartial", rating)
            </div>
        </div>
    }

    @if (User.IsEmployeeOrAdmin())
    {
        @Html.ActionLink("Edit", "EditDownloadGameProduct", new { id = Model.Id }, new { @class = "button expand small" })
        @Html.ActionLink("Delete", "DeleteGameProduct", new { id = Model.Id }, new { @class = "button expand small alert" })
    }
    else
    {
        <a href="@Model.DownloadLink" class="button expand success">Free Download</a>
    }
</div>