Veil/Veil/Controllers/GameProductsController.cs
/* GameProductsController.cs
 * Purpose: Controller for actions related to the GameProduct model and derived models
 * 
 * Revision History:
 *      Kyle Zimmerman, 2015.11.9: Created
 */ 

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Veil.DataAccess.Interfaces;
using Veil.DataModels;
using Veil.DataModels.Models;
using Veil.Helpers;
using Veil.Models;

namespace Veil.Controllers
{
    /// <summary>
    ///     Controller for actions related to <see cref="GameProduct"/>
    /// </summary>
    public class GameProductsController : BaseController
    {
        private readonly IVeilDataAccess db;
        private readonly IGuidUserIdGetter idGetter;

        /// <summary>
        ///     Instantiates a new instance of GameProductsController with the provided arguments
        /// </summary>
        /// <param name="veilDataAccess">
        ///     The <see cref="IVeilDataAccess"/> to use for database access
        /// </param>
        /// <param name="idGetter">
        ///     The <see cref="IGuidUserIdGetter"/> to use for getting the current user's Id
        /// </param>
        public GameProductsController(IVeilDataAccess veilDataAccess, IGuidUserIdGetter idGetter)
        {
            db = veilDataAccess;
            this.idGetter = idGetter;
        }

        /// <summary>
        ///     Renders the Game SKU partial for a physical game product
        /// </summary>
        /// <param name="gameProduct">
        ///     The physical game sku to render.
        /// </param>
        /// <returns>
        ///     Partial view containing the information specific to PhysicalGameProducts
        /// </returns>
        [ChildActionOnly]
        public PartialViewResult RenderPhysicalGameProductPartial(PhysicalGameProduct gameProduct)
        {
            PhysicalGameProductViewModel model = new PhysicalGameProductViewModel
            {
                GameProduct = gameProduct
            };

            Member currentMember = db.Members.Find(idGetter.GetUserId(User.Identity));

            if (currentMember != null)
            {
                model.NewIsInCart = currentMember.Cart.Items.
                    Any(i => i.ProductId == gameProduct.Id && i.IsNew);

                model.UsedIsInCart = currentMember.Cart.Items.
                    Any(i => i.ProductId == gameProduct.Id && !i.IsNew);

                model.ProductIsOnWishlist = currentMember.Wishlist.
                    Any(p => p.Id == gameProduct.Id);
            }

            return PartialView("_PhysicalGameProductPartial", model);
        }

        /// <summary>
        ///     Displays a delete confirmation page for the identified game SKU
        /// </summary>
        /// <param name="id">
        ///     The Id of the game SKU to delete
        /// </param>
        /// <returns>
        ///     The delete confirmation page if a match is found
        ///     404 Not Found page if a match is not found
        /// </returns>
        [Authorize(Roles = VeilRoles.Authorize.Admin_Employee)]
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                throw new HttpException(NotFound, "There was an error");
            }

            GameProduct gameProduct = await db.GameProducts.FindAsync(id);

            if (gameProduct == null)
            {
                //replace this when it is finished
                throw new HttpException(NotFound, "There was an error");
            }

            return View(gameProduct);
        }

        /// <summary>
        ///     Deletes the identified game including all of its empty ProductLocationInventories
        /// </summary>
        /// <param name="id">
        ///     The Id of the game SKU to delete
        /// </param>
        /// <returns>
        ///     Redirection to Games/Index if successful
        ///     Redirection to Delete to redisplay the confirmation page if unsuccessful
        ///     404 Not Found if no game matches the Id
        /// </returns>
        [Authorize(Roles = VeilRoles.Authorize.Admin_Employee)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            GameProduct gameProduct = await db.GameProducts.
                Include(gp => gp.Game).
                Include(gp => gp.Platform).
                SingleOrDefaultAsync(gp => gp.Id == id);

            if (gameProduct == null)
            {
                throw new HttpException(NotFound, "Game SKU");
            }

            string gameName = gameProduct.Game.Name;
            string platform = gameProduct.Platform.PlatformName;

            try
            {
                db.ProductLocationInventories.RemoveRange(
                    await db.ProductLocationInventories.Where(
                        pli =>
                            pli.ProductId == id &&
                                pli.NewOnHand == 0 &&
                                pli.UsedOnHand == 0 &&
                                pli.NewOnOrder == 0).ToListAsync()
                    );

                db.GameProducts.Remove(gameProduct);

                await db.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                // Get the exception which states if a foreign key constraint was violated
                SqlException innermostException = ex.GetBaseException() as SqlException;

                bool errorWasConstraintViolation = false;

                if (innermostException != null)
                {
                    errorWasConstraintViolation =
                        innermostException.Number == (int) SqlErrorNumbers.ConstraintViolation;
                }

                if (errorWasConstraintViolation)
                {
                    this.AddAlert(
                        AlertType.Error,
                        "Other portions of our system depend on this Game SKU's data." +
                            " Consider marking it as not for sale instead.");
                }
                else
                {
                    this.AddAlert(
                        AlertType.Error, $"There was an error deleting {gameName} for {platform}.");
                }

                return RedirectToAction("Delete", new { id = id });
            }

            this.AddAlert(AlertType.Success, $"{gameName} for {platform} was deleted succesfully.");

            return RedirectToAction("Index", "Games");
        }

        /// <summary>
        /// A view to create a new PhysicalGameProduct
        /// </summary>
        /// <param name="id">The ID of the game to add this product to</param>
        /// <returns>
        ///     Redirects to the Game Details page if successful
        ///     Redirects to the Game List page if the id does not match an existing Game.
        /// </returns>
        [Authorize(Roles = VeilRoles.Authorize.Admin_Employee)]
        public async Task<ActionResult> CreatePhysicalSKU(Guid id)
        {
            if (!await db.Games.AnyAsync(g => g.Id == id))
            {
                throw new HttpException(NotFound, "Game");
            }

            SetupGameProductSelectLists();

            return View();
        }

        /// <summary>
        /// Creates an saves a new PhysicalGameProduct to the database.
        /// </summary>
        /// <param name="id">The ID of the game to add this product to</param>
        /// <param name="gameProduct">The PhysicalGameProduct to add to the game</param>
        /// <returns>
        ///     Redirects to the Game Details page if successful
        ///     A view of the create screen with validation errors if there were any
        ///     Redirects to the Game List if the id doesn't match an existing Game.
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = VeilRoles.Authorize.Admin_Employee)]
        public async Task<ActionResult> CreatePhysicalSKU(
            Guid id,
            [Bind(
                Exclude =
                    nameof(PhysicalGameProduct.NewInventory) + "," +
                        nameof(PhysicalGameProduct.UsedInventory))] PhysicalGameProduct gameProduct)
        {
            if (!await db.Games.AnyAsync(g => g.Id == id))
            {
                throw new HttpException(NotFound, nameof(Game));
            }

            if (ModelState.IsValid)
            {
                var internalSku = db.GetNextPhysicalGameProductSku();

                gameProduct.InteralUsedSKU = $"1{internalSku}";
                gameProduct.InternalNewSKU = $"0{internalSku}";

                return await SaveGameProduct(id, gameProduct);
            }

            SetupGameProductSelectLists();

            return View(gameProduct);
        }

        /// <summary>
        /// Displays existing information for a Physical Game Product and allows the user to edit it.
        /// </summary>
        /// <param name="id">The ID of the Physical Game Product to edit</param>
        /// <returns>
        ///     Edit view if the Id is for a physical game product
        ///     404 Not Found view if the Id couldn't be matched to a game product
        /// </returns>
        [Authorize(Roles = VeilRoles.Authorize.Admin_Employee)]
        public async Task<ActionResult> EditPhysicalSKU(Guid? id)
        {
            if (id == null)
            {
                throw new HttpException(NotFound, "Physical Game Product");
            }

            var physicalGameProduct = await db.PhysicalGameProducts.FirstOrDefaultAsync(p => p.Id == id);

            if (physicalGameProduct == null)
            {
                throw new HttpException(NotFound, "Physical Game Product");
            }

            SetupGameProductSelectLists();

Veil/Veil/Views/GameProducts/CreateDownloadSKU.cshtml
@model Veil.DataModels.Models.DownloadGameProduct

@{
    ViewBag.Title = "Create Downloadable Game Product";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="medium-10 medium-centered  column">
            <h2>@ViewBag.Title</h2>
            @Html.ValidationSummary(true)

            <h3>@Html.Encode(Model?.Game?.Name ?? "")</h3>

            <fieldset>
                <legend>Game Details</legend>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.SKUDescription, htmlAttributes: new { @class = "prefix" })
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.SKUDescription, new { htmlAttributes = new { @class = "expand" } })
                        @Html.ValidationMessageFor(model => model.SKUDescription, "", new { @class = "" })
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.PlatformCode, htmlAttributes: new {@class = "prefix"})
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.DropDownListFor(model => model.PlatformCode, null, new {htmlAttributes = new {@class = "expand"}})
                        @Html.ValidationMessageFor(model => model.PlatformCode, "", new {@class = ""})
                    </div>
                </div>

                <div class="row">
                    <div class="medium-6 columns">
                        <div class="row collapse">
                            <div class="small-12 medium-8 large-4 columns">
                                @Html.LabelFor(model => model.DeveloperId, htmlAttributes: new {@class = "prefix"})
                            </div>
                            <div class="medium-4 large-8 columns">
                                @Html.DropDownListFor(model => model.DeveloperId, null, new {htmlAttributes = new {@class = "expand"}})
                                @Html.ValidationMessageFor(model => model.DeveloperId, "", new {@class = ""})
                            </div>
                        </div>
                    </div>
                    <div class="medium-6 columns">
                        <div class="row collapse">
                            <div class="small-12 medium-8 large-4 columns">
                                @Html.LabelFor(model => model.PublisherId, htmlAttributes: new {@class = "prefix"})
                            </div>
                            <div class="medium-4 large-8 columns">
                                @Html.DropDownListFor(model => model.PublisherId, null, new {htmlAttributes = new {@class = "expand"}})
                                @Html.ValidationMessageFor(model => model.PublisherId, "", new {@class = ""})
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.BoxArtImageURL, htmlAttributes: new {@class = "prefix"})
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.BoxArtImageURL, new {htmlAttributes = new {@class = "expand"}})
                        @Html.ValidationMessageFor(model => model.BoxArtImageURL, "", new {@class = ""})
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new {@class = "prefix"})
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.ReleaseDate, new {htmlAttributes = new {@class = "expand"}})
                        @Html.ValidationMessageFor(model => model.ReleaseDate, "", new {@class = ""})
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Download Info</legend>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.DownloadLink, htmlAttributes: new {@class = "prefix"})
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.DownloadLink, new {htmlAttributes = new {@class = "expand"}})
                        @Html.ValidationMessageFor(model => model.DownloadLink, "", new {@class = ""})
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.ApproximateSizeInMB, htmlAttributes: new {@class = "prefix"})
                    </div>
                    <div class="small-10 medium-7 large-9 columns">
                        @Html.EditorFor(model => model.ApproximateSizeInMB, new {htmlAttributes = new {@class = "expand"}})
                        @Html.ValidationMessageFor(model => model.ApproximateSizeInMB, "", new {@class = ""})
                    </div>
                    <div class="small-2 medium-1 columns">
                        <span class="postfix">MB</span>
                    </div>
                </div>
            </fieldset>

            <button type="submit" class="expand">Create Game Product</button>
        </div>
    </div>
}

Veil/Veil/Views/GameProducts/CreatePhysicalSKU.cshtml
@model Veil.DataModels.Models.PhysicalGameProduct

@{
    ViewBag.Title = "Create Physical Game Product";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="medium-10 medium-centered  column">
            <h2>@ViewBag.Title</h2>
            @Html.ValidationSummary(true)

            <h3>@Html.Encode(Model?.Game?.Name ?? "")</h3>

            <fieldset>
                <legend>Game Details</legend>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.SKUNameSuffix, htmlAttributes: new {@class = "prefix"})
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.SKUNameSuffix, new {htmlAttributes = new {@class = "expand", placeholder="E.g. Collectors Edition"}})
                        @Html.ValidationMessageFor(model => model.SKUDescription, "", new {@class = ""})
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.SKUDescription, htmlAttributes: new { @class = "prefix" })
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.SKUDescription, new { htmlAttributes = new { @class = "expand" } })
                        @Html.ValidationMessageFor(model => model.SKUDescription, "", new { @class = "" })
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.PlatformCode, htmlAttributes: new { @class = "prefix" })
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.DropDownListFor(model => model.PlatformCode, null, new { htmlAttributes = new { @class = "expand" } })
                        @Html.ValidationMessageFor(model => model.PlatformCode, "", new { @class = "" })
                    </div>
                </div>

                <div class="row">
                    <div class="medium-6 columns">
                        <div class="row collapse">
                            <div class="small-12 medium-8 large-4 columns">
                                @Html.LabelFor(model => model.DeveloperId, htmlAttributes: new { @class = "prefix" })
                            </div>
                            <div class="medium-4 large-8 columns">
                                @Html.DropDownListFor(model => model.DeveloperId, null, new { htmlAttributes = new { @class = "expand" } })
                                @Html.ValidationMessageFor(model => model.DeveloperId, "", new { @class = "" })
                            </div>
                        </div>
                    </div>
                    <div class="medium-6 columns">
                        <div class="row collapse">
                            <div class="small-12 medium-8 large-4 columns">
                                @Html.LabelFor(model => model.PublisherId, htmlAttributes: new { @class = "prefix" })
                            </div>
                            <div class="medium-4 large-8 columns">
                                @Html.DropDownListFor(model => model.PublisherId, null, new { htmlAttributes = new { @class = "expand" } })
                                @Html.ValidationMessageFor(model => model.PublisherId, "", new { @class = "" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.BoxArtImageURL, htmlAttributes: new { @class = "prefix" })
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.BoxArtImageURL, new { htmlAttributes = new { @class = "expand" } })
                        @Html.ValidationMessageFor(model => model.BoxArtImageURL, "", new { @class = "" })
                    </div>
                </div>

                <div class="row collapse">
                    <div class="small-12 medium-4 large-2 columns">
                        @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "prefix" })
                    </div>
                    <div class="medium-8 large-10 columns">
                        @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "expand" } })
                        @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "" })
                    </div>
                </div>
            </fieldset>

            <div class="row" data-equalizer>
                <div class="medium-6 columns">
                    <fieldset data-equalizer-watch>
                        <legend>New Details</legend>

                        <div class="row collapse">
                            <div class="small-12 medium-4 columns">
                                @Html.LabelFor(model => model.ProductAvailabilityStatus, htmlAttributes: new { @class = "prefix" })
                            </div>
                            <div class="medium-8 columns">
                                @Html.EnumDropDownListFor(model => model.ProductAvailabilityStatus, new { htmlAttributes = new { @class = "expand" } })
                                @Html.ValidationMessageFor(model => model.ProductAvailabilityStatus, "", new { @class = "" })
                            </div>
                        </div>

                        <div class="row collapse">
                            <div class="small-12 medium-4 columns">
                                @Html.LabelFor(model => model.NewWebPrice, htmlAttributes: new { @class = "prefix" })
                            </div>
                            <div class="medium-8 columns">
                                @Html.EditorFor(model => model.NewWebPrice, new { htmlAttributes = new { @class = "expand" } })
                                @Html.ValidationMessageFor(model => model.NewWebPrice, "", new { @class = "" })
                            </div>
                        </div>
                    </fieldset>
                </div>

                <div class="medium-6 columns">
                    <fieldset data-equalizer-watch>
                        <legend>Used Details</legend>

                        <div class="row collapse">
                            <div class="small-12 medium-4 columns">
                                @Html.LabelFor(model => model.WillBuyBackUsedCopy, htmlAttributes: new { @class = "prefix" })
                            </div>
                            <div class="medium-8 columns panel">
                                @Html.EditorFor(model => model.WillBuyBackUsedCopy, new { htmlAttributes = new { @class = "expand" } })
                                @Html.ValidationMessageFor(model => model.WillBuyBackUsedCopy, "", new { @class = "" })
                            </div>
                        </div>

                        <div class="row collapse">
                            <div class="small-12 medium-4 columns">
                                @Html.LabelFor(model => model.UsedWebPrice, htmlAttributes: new { @class = "prefix" })
                            </div>
                            <div class="medium-8 columns">
                                @Html.EditorFor(model => model.UsedWebPrice, new { htmlAttributes = new { @class = "expand" } })
                                @Html.ValidationMessageFor(model => model.UsedWebPrice, "", new { @class = "" })
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>

            <button type="submit" class="expand">Create Game Product</button>
        </div>
    </div>
}

Veil/Veil/Views/GameProducts/Delete.cshtml
@model Veil.DataModels.Models.GameProduct

@{
    ViewBag.Title = "Delete Game SKU";
}

<div class="row">
    <div class="column">
        <h2>Delete "@Model.Name" for @Model.Platform.PlatformName</h2>
    </div>
</div>

<div class="row">
    <div class="columns">
        <h3>Are you sure you want to delete this game SKU?</h3>
        <hr />

        <p>
            <strong>@Html.DisplayNameFor(m => m.Developer):</strong>
            @Model.Developer.Name
        </p>

        <p>
            <strong>@Html.DisplayNameFor(m => m.Publisher):</strong>
            @Model.Publisher.Name
        </p>

        <p>
            <strong>@Html.DisplayNameFor(m => m.ReleaseDate):</strong>
            @Model.ReleaseDate.ToShortDateString()
        </p>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ActionLink("Cancel", "Details", new { Controller= "Games", Id = Model.GameId }, new { @class = "button"})

            <button type="submit" class="alert right">Delete</button>
        }
    </div>
</div>

Veil/Veil/Views/GameProducts/_DownloadGameProduct.cshtml
@using Veil.DataModels.Models
@using Veil.Extensions
@model DownloadGameProduct

<div class="medium-3 columns" data-equalizer-watch>
    @{ var rating = Model.AverageRating; }
    @if (rating.HasValue)
    {
        <div class="row">
            <strong class="label info column bordered">Average Rating</strong>
        </div>

        <div class="row">
            <div class="column text-center margin-bottom-1 bordered rating">
                @Html.Partial("_RatingStarsPartial", rating)
            </div>
        </div>
    }

    @if (User.IsEmployeeOrAdmin())
    {
        @Html.ActionLink("Edit", "EditDownloadSKU", "GameProducts", new { id = Model.Id }, new { @class = "button expand small" })
        @Html.ActionLink("Delete", "Delete", "GameProducts", new { id = Model.Id }, new { @class = "button expand small alert" })
    }
    else
    {
        <a href="@Model.DownloadLink" class="button expand success">Free Download</a>
    }
</div>

Veil/Veil/Views/GameProducts/_GameProductPartial.cshtml
@using Veil.DataModels.Models
@model GameProduct


<div class="medium-1 columns" data-equalizer-watch>
    <h4 class="platform-transform">@Model.Platform.PlatformName</h4>
</div>

<div class="medium-2 columns" data-equalizer-watch>
    <img src="@Model.BoxArtImageURL" alt="@Model.PlatformCode Box Art"/>
</div>

<div class="medium-6 columns" data-equalizer-watch>
    <h5>@Model.Name</h5>
    <p class="margin-bottom-0 padding-bottom-half-em">@Model.SKUDescription</p>
    @if (Model.ReleaseDate > DateTime.Now)
    {
        <p class="margin-bottom-0">
            <strong>Release Date:</strong>&nbsp;@Model.ReleaseDate.ToString("MMM dd, yyyy")
        </p>
    }
    <p class="margin-bottom-0"><strong>Developer:</strong>&nbsp;@Model.Developer.Name</p>
    <p class="margin-bottom-0"><strong>Publisher:</strong>&nbsp;@Model.Publisher.Name</p>
</div>

Veil/Veil/Views/GameProducts/_PhysicalGameProductPartial.cshtml
@using Veil.DataModels.Models
@using Veil.Models
@using Veil.Extensions
@model PhysicalGameProductViewModel

<div class="medium-3 columns" data-equalizer-watch>
    @{ var rating = Model.GameProduct.AverageRating; }
    @if (rating.HasValue)
    {
        <div class="row">
            <strong class="label info column bordered">Average Rating</strong>
        </div>

        <div class="row">
            <div class="column text-center margin-bottom-1 bordered rating">
                @Html.Partial("_RatingStarsPartial", rating)
            </div>
        </div>
    }

    @if (User.IsEmployeeOrAdmin())
    {
        @Html.ActionLink("Edit", "EditPhysicalSKU", new { id = Model.GameProduct.Id }, new { @class = "button expand small" })
        @Html.ActionLink("Delete", "Delete", new { id = Model.GameProduct.Id }, new { @class = "button expand small alert" })
    }
    else
    {
        string buyNewClasses = "button expand small success margin-bottom-0";
        string buyNewText = "Buy New";

        if (Model.GameProduct.ReleaseDate > DateTime.Now)
        {
            buyNewText = "Pre-order";
        }

        if (Model.NewIsInCart)
        {
            <a class="@buyNewClasses disabled">@($"{buyNewText} {Model.GameProduct.NewWebPrice:C} (in your cart)")</a>
        }
        else if (Model.GameProduct.ProductAvailabilityStatus == AvailabilityStatus.DiscontinuedByManufacturer &&
            Model.GameProduct.NewInventory < 1)
        {
            <a class="@buyNewClasses disabled">@($"{buyNewText} {Model.GameProduct.NewWebPrice:C} (unavailable)")</a>
        }
        else
        {
            @Html.ActionLink($"{buyNewText} {Model.GameProduct.NewWebPrice:C}", "AddItem", "Cart", 
                new { productId = Model.GameProduct.Id, isNew = true }, 
                new { @class = buyNewClasses })
        }

        if (Model.GameProduct.UsedWebPrice.HasValue)
        {
            string buyUsedClasses = "button expand small margin-bottom-0";

            if (Model.UsedIsInCart)
            {
                <a class="@buyUsedClasses disabled">Buy Used @($"{Model.GameProduct.UsedWebPrice.Value:C} (in your cart)")</a>
            }
            else if (Model.GameProduct.UsedInventory < 1)
            {
                <a class="@buyUsedClasses disabled">Buy Used @($"{Model.GameProduct.UsedWebPrice.Value:C} (unavailable)")</a>
            }
            else
            {
                @Html.ActionLink($"Buy Used {Model.GameProduct.UsedWebPrice.Value:C}", "AddItem", "Cart",
                    new { productId = Model.GameProduct.Id, isNew = false },
                    new { @class = buyUsedClasses })
            }
        }

        string wishlistClasses = "button expand small info margin-bottom-0";
        if (Model.ProductIsOnWishlist)
        {
            <a class="@wishlistClasses disabled">On Your Wishlist</a>
        }
        else
        {
            @Html.ActionLink("Add to Wishlist", "Add", "Wishlist",
                new { itemId = Model.GameProduct.Id },
                new { @class = wishlistClasses })
        }
    }
</div>