Veil/Veil/Controllers/FriendListController.cs
/* FriendListController.cs
 * Purpose: Controller for friend list related actions
 * 
 * Revision History:
 *      Drew Matheson, 2015.10.15: Created
 */ 

using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Veil.DataAccess.Interfaces;
using Veil.DataModels;
using Veil.DataModels.Models;
using Veil.Helpers;
using Veil.Models;

namespace Veil.Controllers
{
    /// <summary>
    ///     Controller for Friendship related actions
    /// </summary>
    [Authorize(Roles = VeilRoles.MEMBER_ROLE)]
    public class FriendListController : BaseController
    {
        private readonly IVeilDataAccess db;
        private readonly IGuidUserIdGetter idGetter;

        /// <summary>
        ///     Instantiates a new instance of FriendListController with the provided arguments
        /// </summary>
        /// <param name="veilDataAccess">
        ///     The <see cref="IVeilDataAccess"/> to use for database access
        /// </param>
        /// <param name="idGetter">
        ///     The <see cref="IGuidUserIdGetter"/> to use for getting the current user's Id
        /// </param>
        public FriendListController(IVeilDataAccess veilDataAccess, IGuidUserIdGetter idGetter)
        {
            db = veilDataAccess;
            this.idGetter = idGetter;
        }

        /// <summary>
        ///     Displays a view showing a list of friends and requests sent/received for the user
        /// </summary>
        /// <returns>
        ///     The view displaying the friend list
        /// </returns>
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            FriendsListViewModel friendsListViewModel = new FriendsListViewModel
            {
                ConfirmedFriends = new List<Member>(),
                PendingReceivedFriendships = new List<Member>(),
                PendingSentFriendships = new List<Member>()
            };

            Guid currentMemberId = idGetter.GetUserId(User.Identity);

            Member member = await db.Members
                .Include(m => m.RequestedFriendships)
                .Include(m => m.ReceivedFriendships)
                .Where(m => m.UserId == currentMemberId)
                .FirstOrDefaultAsync();

            var friendships = member.RequestedFriendships
                .Concat(member.ReceivedFriendships).ToList();

            friendsListViewModel.ConfirmedFriends = member.ConfirmedFriends.ToList();

            var pendingReceivedFriendships = friendships
                .Where(f => f.RequestStatus == FriendshipRequestStatus.Pending &&
                            f.ReceiverId == currentMemberId);

            foreach (var friendship in pendingReceivedFriendships)
            {
                friendsListViewModel.PendingReceivedFriendships
                    .Add(friendship.Requester);
            }

            var pendingSentFriendships = friendships
                .Where(f => f.RequestStatus == FriendshipRequestStatus.Pending &&
                            f.RequesterId == currentMemberId);

            foreach (var friendship in pendingSentFriendships)
            {
                friendsListViewModel.PendingSentFriendships
                    .Add(friendship.Receiver);
            }

            return View(friendsListViewModel);
        }

        /// <summary>
        ///     Processes a friends request made by the user.
        /// </summary>
        /// <param name="username">
        ///     The username entered by the user.
        /// </param>
        /// <returns>
        ///     Redirect to 'Index' action.
        /// </returns>
        [HttpPost]
        public async Task<ActionResult> AddFriendRequest(string username)
        {
            Guid currentMemberGuid = idGetter.GetUserId(User.Identity);

            Member currentUser = await db.Members
                .Where(m => m.UserId == currentMemberGuid)
                .FirstOrDefaultAsync();

            Member targetUser = await db.Members
                .Where(m => m.UserAccount.UserName == username)
                .FirstOrDefaultAsync();

            if (currentUser == targetUser)
            {
                this.AddAlert(AlertType.Error, "Cannot add yourself as a friend.");

                return RedirectToAction("Index");
            }

            if (targetUser == null)
            {
                this.AddAlert(AlertType.Error, $"No member with the username '{username}' exists.");

                return RedirectToAction("Index");
            }

            Friendship existingFriendship = await db.Friendships
                .Where(
                    f =>
                        (f.Requester.UserId == currentUser.UserId && f.Receiver.UserId == targetUser.UserId) ||
                            (f.Requester.UserId == targetUser.UserId &&
                                f.Receiver.UserId == currentUser.UserId))
                .FirstOrDefaultAsync();

            if (existingFriendship == null)
            {
                Friendship friendship = new Friendship()
                {
                    RequesterId = currentUser.UserId,
                    ReceiverId = targetUser.UserId,
                    RequestStatus = FriendshipRequestStatus.Pending
                };

                db.Friendships.Add(friendship);
                await db.SaveChangesAsync();

                this.AddAlert(AlertType.Success, $"Request sent to {targetUser.UserAccount.UserName}.");
            }
            else if (existingFriendship.RequestStatus == FriendshipRequestStatus.Accepted)
            {
                this.AddAlert(
                    AlertType.Info, $"You are already friends with {targetUser.UserAccount.UserName}.");
            }
            else if (existingFriendship.Requester == currentUser)
            {
                this.AddAlert(
                    AlertType.Info, $"Request already sent to {targetUser.UserAccount.UserName}.");
            }
            else if (existingFriendship.Receiver == currentUser)
            {
                existingFriendship.RequestStatus = FriendshipRequestStatus.Accepted;

                await db.SaveChangesAsync();

                this.AddAlert(
                    AlertType.Success, $"Request from {targetUser.UserAccount.UserName} approved.");
            }

            return RedirectToAction("Index");
        }

        /// <summary>
        ///     Approves a received friend request.
        /// </summary>
        /// <param name="memberId">
        ///     The GUID of the requesting user.
        /// </param>
        /// <returns>
        ///     Redirect to 'Index' action.
        /// </returns>
        public async Task<ActionResult> Approve(Guid memberId)
        {
            Guid currentMemberGuid = idGetter.GetUserId(User.Identity);

            Friendship existingFriendship = await db.Friendships
                .Where(
                    f => (f.Requester.UserId == currentMemberGuid && f.Receiver.UserId == memberId) ||
                        (f.Requester.UserId == memberId && f.Receiver.UserId == currentMemberGuid))
                .FirstOrDefaultAsync();

            if (existingFriendship == null)
            {
                return RedirectToAction("Index");
            }

            existingFriendship.RequestStatus = FriendshipRequestStatus.Accepted;
            await db.SaveChangesAsync();

            this.AddAlert(AlertType.Success, "Friend request approved.");

            return RedirectToAction("Index");
        }

        /// <summary>
        ///     Declines the a received friend request.
        /// </summary>
        /// <param name="memberId">
        ///     The GUID of the requesting user.
        /// </param>
        /// <returns>
        ///     Result from Delete method.
        /// </returns>
        public async Task<ActionResult> Decline(Guid memberId)
        {
            this.AddAlert(AlertType.Success, "Friend request declined.");

            Task<ActionResult> result = Delete(memberId);

            return await result;
        }

        /// <summary>
        ///     Removes a friend from the user's friend list.
        /// </summary>
        /// <param name="memberId">
        ///     The GUID of the user being removed from the friend list.
        /// </param>
        /// <returns>
        ///     Result from Delete method.
        /// </returns>
        public async Task<ActionResult> Remove(Guid memberId)
        {
            this.AddAlert(AlertType.Success, "Friend removed.");

            Task<ActionResult> result = Delete(memberId);

            return await result;
        }

        /// <summary>
        ///     Cancels the current user's friend request sent to another user.
        /// </summary>
        /// <param name="memberId">
        ///     The GUID of the requested user.
        /// </param>
        /// <returns>
        ///     Result from Delete method.
        /// </returns>
        public async Task<ActionResult> Cancel(Guid memberId)
        {
            this.AddAlert(AlertType.Success, "Friend request cancelled.");

            Task<ActionResult> result = Delete(memberId);

            return await result;
        }

        /// <summary>
        ///     Method to delete any friendship between the current user and another user.
        /// </summary>
        /// <param name="memberId">
        ///     The GUID of the requesting/requested/friend user (not the current user).
        /// </param>
        /// <returns>
        ///     Redirect to 'Index' action.
        /// </returns>
        [NonAction]
        private async Task<ActionResult> Delete(Guid memberId)
        {
            Guid currentMemberGuid = idGetter.GetUserId(User.Identity);

            Friendship existingFriendship = await db.Friendships
                .Where(
                    f => (f.Requester.UserId == currentMemberGuid && f.Receiver.UserId == memberId) ||

Veil/Veil/Views/FriendList/Index.cshtml
@using Veil.DataModels.Models
@model Veil.Models.FriendsListViewModel

@{
    ViewBag.Title = "Friends List";
}

<div class="row">
    <div class="columns">
        <h2>@ViewBag.Title</h2>

        <h4>Add a New Friend</h4>
        @using (Html.BeginForm("AddFriendRequest", "FriendList", FormMethod.Post))
        {
            <div class="row collapse">
                <div class="medium-4 small-8 columns">
                    <input type="text" id="username" name="username" placeholder="Your friend's username"/>
                </div>
                <div class="medium-2 small-4 columns">
                    <button type="submit" class="button postfix">Add Friend</button>
                </div>
                <div class="medium-6 columns"></div>
            </div>
        }
    </div>
</div>

<div class="row">
    <div class="medium-9 columns bordered margin-half-em">
        <h4>Requests Pending Action</h4>
        @if (Model.PendingReceivedFriendships.Count > 0)
        {
            foreach (var member in Model.PendingReceivedFriendships)
            {
                <div class="row">
                    <div class="medium-6 columns">@member.UserAccount.UserName</div>
                    <div class="small-6 medium-3 columns">@Html.ActionLink("Approve", "Approve", "FriendList", new { memberId = member.UserId }, new {@class = "button tiny success expand" })</div>
                    <div class="small-6 medium-3 columns">@Html.ActionLink("Decline", "Decline", "FriendList", new { memberId = member.UserId }, new { @class = "button tiny alert expand" })</div>
                </div>
            }
        }
        else
        {
            <div class="row">
                <div class="columns"><em>You have no requests requiring action.</em></div>
            </div>
        }
    </div>
    <div class="medium-9 columns bordered margin-half-em">
        <h4>My Pending Requests</h4>
        @if (Model.PendingSentFriendships.Count > 0)
        {
            foreach (var member in Model.PendingSentFriendships)
            {
                <div class="row">
                    <div class="small-9 columns">@member.UserAccount.UserName</div>
                    <div class="small-3 columns">@Html.ActionLink("Cancel", "Cancel", "FriendList", new { memberId = member.UserId }, new { @class = "button tiny alert expand" })</div>
                </div>
            }
        }
        else
        {
            <div class="row">
                <div class="columns"><em>You have no pending requests.</em></div>
            </div>
        }
    </div>
    <div class="medium-9 end columns bordered margin-half-em">
        <h4>My Friends</h4>
        @if (Model.ConfirmedFriends.Count > 0)
        {
            foreach (var friend in Model.ConfirmedFriends)
            {
                <div class="row">
                    <div class="medium-6 columns">@friend.UserAccount.UserName</div>
                    <div class="small-4 small-offset-4 medium-3 medium-offset-0 columns">@((friend.WishListVisibility == WishListVisibility.Private) 
                            ? new HtmlString("<a class=\"button tiny info expand disabled\">Private</a>")
                            : Html.ActionLink("View Wishlist", "Index", "Wishlist", new { username = friend.UserAccount.UserName }, new { @class = "button tiny info expand expand" }))</div>
                    <div class="small-4 medium-3 columns">@Html.ActionLink("Remove", "Remove", "FriendList", new { memberId = friend.UserId }, new { @class = "button tiny alert expand" })</div>
                </div>
            }
        }
        else
        {
            <div class="row">
                <div class="columns"><em>You have no friends.</em></div>
            </div>
        }
    </div>
</div>